# Generated by Django 4.2.7 on 2026-04-30 14:39

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chaise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_unique', models.CharField(max_length=50, unique=True)),
                ('etat', models.CharField(choices=[('excellent', 'Excellent'), ('bon', 'Bon'), ('usage', 'Usure normale'), ('bancal', 'Bancal'), ('casse', 'Cassée'), ('graffiti', 'Tag/graffiti')], default='bon', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='chaises/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_derniere_modification', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('capacite', models.IntegerField(default=30)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Signalement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_probleme', models.CharField(choices=[('chaise', 'Chaise'), ('ordinateur', 'Ordinateur'), ('autre', 'Autre')], max_length=20)),
                ('objet_id', models.PositiveIntegerField(blank=True, help_text="ID de la chaise ou de l'ordinateur concerné", null=True)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('resolu', models.BooleanField(default=False)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.CharField(choices=[('3', '3ème année'), ('4', '4ème année'), ('5', '5ème année')], max_length=10)),
                ('semestre', models.CharField(choices=[('1', 'Semestre 1'), ('2', 'Semestre 2')], default='1', max_length=10)),
                ('date_seance', models.DateField(default=datetime.date.today)),
                ('commentaire', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seances', to=settings.AUTH_USER_MODEL)),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salle.salle')),
            ],
        ),
        migrations.CreateModel(
            name='RapportSalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('photo', models.ImageField(upload_to='rapports_salle/%Y/%m/%d/')),
                ('commentaire', models.TextField(help_text='État général de la salle, problèmes constatés')),
                ('ordre_general', models.IntegerField(choices=[(1, 'Très désordonné'), (2, 'Désordonné'), (3, 'Correct'), (4, 'Organisé'), (5, 'Très organisé')], default=3)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports', to='salle.salle')),
            ],
        ),
        migrations.CreateModel(
            name='Ordinateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_unique', models.CharField(max_length=50, unique=True)),
                ('etat', models.CharField(choices=[('excellent', 'Excellent'), ('bon', 'Bon'), ('lent', 'Lent'), ('ecran_casse', 'Écran cassé'), ('clavier_hs', 'Clavier HS'), ('souris_hs', 'Souris HS'), ('ne_demarre', 'Ne démarre pas')], default='bon', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='ordinateurs/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_derniere_modification', models.DateTimeField(auto_now=True)),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordinateurs', to='salle.salle')),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=50, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('niveau', models.CharField(choices=[('3', '3ème année'), ('4', '4ème année'), ('5', '5ème année')], max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('date_association', models.DateTimeField(blank=True, null=True)),
                ('date_modification', models.DateTimeField(auto_now=True, null=True)),
                ('chaise_associee', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etudiant_assigne', to='salle.chaise')),
                ('pc_associe', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etudiant_assigne', to='salle.ordinateur')),
            ],
        ),
        migrations.AddField(
            model_name='chaise',
            name='salle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chaises', to='salle.salle'),
        ),
        migrations.CreateModel(
            name='OccupationSeance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chaise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salle.chaise')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salle.etudiant')),
                ('ordinateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salle.ordinateur')),
                ('seance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occupations', to='salle.seance')),
            ],
            options={
                'unique_together': {('seance', 'etudiant')},
            },
        ),
    ]
