# Generated by Django 4.2.7 on 2026-04-30 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaise',
            name='numero',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='ordinateur',
            name='numero',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
